### ISSUE TITLE
Android API<24 compatibility

### ISSUE THREAD

**Issue by Marekp95** [DanySK/java-quadtree#1]
Hi. Could you make release compatible with older versions of android? Java 8 streams are supported only by android version 7.0+ (API level 24) and cause exception at runtime.

**Comment by DanySK** [comment]
Hi,
I got no plan to backport it. However, if you are willing to contribute and backport the library, I am ok with maintaining and publishing a Java 7 compatible version in a separate branch.

**Comment by DanySK** [comment]
#3 solves the issue.
